/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/golfpong/gp_ball.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/gp_ball.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="ball" position={[-0.002, -2.28, -0.004]} rotation={[-0.007, 0, 0]}>
          <mesh name="Cube050" geometry={nodes.Cube050.geometry} material={materials['Material.012']} />
          <mesh name="Cube050_1" geometry={nodes.Cube050_1.geometry} material={materials['Material.011']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gp_ball.glb')
