/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/golfpong/gp_scene.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/gp_scene.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="golfclub" position={[0.006, -2.25, 0.15]} rotation={[3.041, 0.001, 2.725]} scale={0.156}>
          <mesh name="golfclub_primitive0" geometry={nodes.golfclub_primitive0.geometry} material={materials.golf_club} />
          <mesh name="golfclub_primitive1" geometry={nodes.golfclub_primitive1.geometry} material={materials['Material.004']} />
        </group>
        <group name="ball" position={[0, -2.273, 0]} rotation={[0, -1.556, 0]} scale={0.038}>
          <mesh name="ball_primitive0" geometry={nodes.ball_primitive0.geometry} material={materials.Material} />
          <mesh name="ball_primitive1" geometry={nodes.ball_primitive1.geometry} material={materials['Material.001']} />
        </group>
        <mesh name="targetmat" geometry={nodes.targetmat.geometry} material={materials['Material.006']} position={[0, -2.025, -5.437]} rotation={[-2.655, 0, -Math.PI]} scale={[-0.654, -0.014, -0.654]} />
        <mesh name="platform" geometry={nodes.platform.geometry} material={materials['__GLTFLoader._default']} position={[0, -2.344, -2.775]} scale={[1.517, 3.437, 3.437]} />
        <mesh name="puttingg_green_primitive0" geometry={nodes.puttingg_green_primitive0.geometry} material={materials['Material.003']} position={[0, -2.344, 0]} scale={[0.185, 0.185, 0.186]} />
        <mesh name="puttingg_green_primitive1" geometry={nodes.puttingg_green_primitive1.geometry} material={materials['a.grass']} position={[0, -2.344, 0]} scale={[0.185, 0.185, 0.186]} />
        <mesh name="ring4_primitive1" geometry={nodes.ring4_primitive1.geometry} material={materials['Material.005']} position={[-0.393, -1.814, -5.801]} rotation={[0.485, 0, 0]} scale={[0.192, 0.159, 0.192]} />
      </group>
    </group>
  )
}

useGLTF.preload('/gp_scene.glb')
