/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/golfpong/gp_scene.glb 
*/

import React, { useEffect, useRef, useState } from "react";
import { KTX2Loader } from "three/examples/jsm/Addons.js";
import * as THREE from "three";
import { useGLTF, useAnimations, Line, Trail } from "@react-three/drei";
import { useThree, useFrame } from "@react-three/fiber";
import { useExperience } from "../hooks/useExperience";
import useAnimationHelper from "../hooks/useAnimationHelper";
import { useControls, button } from "leva";
import { DissolveMaterial } from "../utils/DissolveMaterial";
import { CustomTrail } from "./CustomTrail";

export default function GolfBallTrail(props) {
  const group = React.useRef();
  const ballRef = useRef();
  const isBallMoving = useRef(false);
  const trailRef = useRef([]);
  const [, setRerender] = useState(0);
  const stillFrames = useRef(0);
  const [dissolveVisible, setDissolveVisible] = useState(false);

  const prevPosRef = useRef(new THREE.Vector3());
  const lastLoggedTrailPoint = useRef(null);
  const lastPoint = trailRef.current[trailRef.current.length - 1];
  const trailKey = lastPoint
    ? `${lastPoint.x},${lastPoint.y},${lastPoint.z}`
    : "empty";

  const [trail, setTrail] = useState([]);
  const gl = useThree((state) => state.gl);
  // KTX2Loader logic for KTX2-compressed textures
  const { nodes, materials, animations } = useGLTF(
    "/golfpong/gp_scene.glb",
    undefined,
    undefined,
    (loader) => {
      const ktx2loader = new KTX2Loader();
      ktx2loader.setTranscoderPath(
        "https://cdn.jsdelivr.net/gh/pmndrs/drei-assets/basis/"
      );
      ktx2loader.detectSupport(gl);
      loader.setKTX2Loader(ktx2loader);
    }
  );
  const { actions } = useAnimations(animations, group);
  const animationNames = Object.keys(actions);
  const animationHelper = useAnimationHelper(actions, animationNames, group);

  const { golfSwingState } = useExperience();

  useControls("BALL Controls", {
    Play_Animation: button(() => {
      if (!actions || Object.keys(actions).length === 0) return;
      Object.values(actions).forEach((action) => {
        if (action) {
          action.reset();
          action.setLoop(THREE.LoopOnce, 1);
          action.clampWhenFinished = true;
          action.paused = false;
          action.play();
        }
      });
    }),
    Dissolve: button(() => setDissolveVisible((prev) => !prev)),
  });

//   useFrame(() => {
//   if (ballRef.current) {
//     const pos = new THREE.Vector3();
//     ballRef.current.getWorldPosition(pos);
//     console.log("Ball world position:", pos);
//   }
// });

  return (
    <group ref={group} {...props} dispose={null}>
      <CustomTrail
        width={0.2}
        color="hotpink"
        length={5}
        decay={1.5}
        local={false}
        stride={0.01}
        interval={5}
      >
        <group
          ref={ballRef}
          name="ball"
          position={[0, -2.273, 0]}
          rotation={[0, -1.556, 0]}
          scale={0.038}
        >
          <mesh
            name="ball_primitive0"
            geometry={nodes.ball_primitive0.geometry}
            material={materials.Material}
          />
          <mesh
            name="ball_primitive1"
            geometry={nodes.ball_primitive1.geometry}
            material={materials["Material.001"]}
          />
        </group>
      </CustomTrail>
    </group>
  );
}

// useGLTF.preload("/golfpong/gp_scene.glb");
