/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/golfpong/gp_scene3.glb 
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import useExperience from "../hooks/useExperience";
import { DissolveMaterial } from "../utils/DissolveMaterial";

export function GP_MainScene(props) {
  const group = React.useRef();

  const { nodes, materials } = useGLTF("/golfpong/gp_scene3.glb");
  const { holes, shotDirection, dissolvingHoles, targetIdx } = useExperience();

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -2.354, 0]} scale={[0.185, 0.185, 0.186]}>
        <mesh
          geometry={nodes.Cube020.geometry}
          material={materials["a.grass"]}
        />
        <mesh
          geometry={nodes.Cube020_1.geometry}
          material={materials["Material.013"]}
        />
      </group>
      <mesh
        geometry={nodes.platform.geometry}
        material={materials["a.grass.002"]}
        position={[0, -2.344, -4.785]}
        scale={[9.179, 5.787, 15.543]}
      />
      <group position={[-0.008, -2.161, -5.347]} rotation={[0.261, 0, 0]}>
        <mesh
          geometry={nodes.Plane017.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane017_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Plane017_2.geometry}
          material={materials["Material.014"]}
        />
      </group>
      <mesh
        geometry={nodes.logo.geometry}
        material={materials["Material.002"]}
        position={[0.401, -2.281, -4.896]}
        rotation={[0.261, 0, 0]}
        scale={[0.212, 0.212, 0.183]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials["Material.008"]}
        position={[0.644, -1.99, -5.975]}
        rotation={[-1.309, 1.571, 0]}
      />
      <mesh
        geometry={nodes.Cylinder043.geometry}
        material={materials["Material.008"]}
        position={[-0.008, -2.161, -5.347]}
        rotation={[-1.309, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder044.geometry}
        material={materials["Material.008"]}
        position={[0.622, -2.31, -6.061]}
        rotation={[0.261, 0, -Math.PI / 2]}
      />
      {holes[0] && (
        <group
          position={[-0.411, -2.065, -5.673]}
          rotation={[0.261, 0, 0]}
          scale={[0.243, 0.201, 0.243]}
        >
          <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry}>
            {!dissolvingHoles[0] ? (
              <>
                <DissolveMaterial
                  baseMaterial={materials["Material.003"].clone()}
                  visible={true}
                  duration={1}
                  color="#eb5a13"
                />
              </>
            ) : (
              <meshStandardMaterial
                attach="material"
                {...(targetIdx === 0
                  ? materials["a.grass"]
                  : materials["Material.003"])}
              />
            )}
          </mesh>

          <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry}>
            {!dissolvingHoles[0] ? (
              <DissolveMaterial
                baseMaterial={materials["Material.005"].clone()}
                visible={true}
                duration={1}
                color="#eb5a13"
              />
            ) : (
              <meshStandardMaterial
                attach="material"
                {...(targetIdx === 0
                  ? materials["a.grass"]
                  : materials["Material.005"])}
              />
            )}
          </mesh>
        </group>
      )}

      {holes[1] && (
        <group
          position={[-0.007, -2.065, -5.673]}
          rotation={[0.261, 0, 0]}
          scale={[0.243, 0.201, 0.243]}
        >
          <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry}>
            {!dissolvingHoles[1] ? (
              <>
                <DissolveMaterial
                  baseMaterial={materials["Material.003"].clone()}
                  visible={true}
                  duration={1}
                  color="#eb5a13"
                />
              </>
            ) : (
              <meshStandardMaterial
                attach="material"
                {...(targetIdx === 1
                  ? materials["a.grass"]
                  : materials["Material.003"])}
              />
            )}
          </mesh>

          <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry}>
            {!dissolvingHoles[1] ? (
              <DissolveMaterial
                baseMaterial={materials["Material.005"].clone()}
                visible={true}
                duration={1}
                color="#eb5a13"
              />
            ) : (
              <meshStandardMaterial
                attach="material"
                {...(targetIdx === 1
                  ? materials["a.grass"]
                  : materials["Material.005"])}
              />
            )}
          </mesh>
        </group>
      )}

      {holes[2] && (
        <group
          position={[0.395, -2.065, -5.673]}
          rotation={[0.261, 0, 0]}
          scale={[0.243, 0.201, 0.243]}
        >
          <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry}>
            {!dissolvingHoles[2] ? (
              <>
                <DissolveMaterial
                  baseMaterial={materials["Material.003"].clone()}
                  visible={true}
                  duration={1}
                  color="#eb5a13"
                />
              </>
            ) : (
              <meshStandardMaterial
                attach="material"
                {...(targetIdx === 2
                  ? materials["a.grass"]
                  : materials["Material.003"])}
              />
            )}
          </mesh>

          <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry}>
            {!dissolvingHoles[2] ? (
              <DissolveMaterial
                baseMaterial={materials["Material.005"].clone()}
                visible={true}
                duration={1}
                color="#eb5a13"
              />
            ) : (
              <meshStandardMaterial
                attach="material"
                {...(targetIdx === 2
                  ? materials["a.grass"]
                  : materials["Material.005"])}
              />
            )}
          </mesh>
        </group>
      )}

      {holes[3] && (
        <group
          position={[-0.21, -2.155, -5.336]}
          rotation={[0.261, 0, 0]}
          scale={[0.243, 0.201, 0.243]}
        >
          <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry}>
            {!dissolvingHoles[3] ? (
              <>
                <DissolveMaterial
                  baseMaterial={materials["Material.003"].clone()}
                  visible={true}
                  duration={1}
                  color="#eb5a13"
                />
              </>
            ) : (
              <meshStandardMaterial
                attach="material"
                {...(targetIdx === 3
                  ? materials["a.grass"]
                  : materials["Material.003"])}
              />
            )}
          </mesh>

          <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry}>
            {!dissolvingHoles[3] ? (
              <DissolveMaterial
                baseMaterial={materials["Material.005"].clone()}
                visible={true}
                duration={1}
                color="#eb5a13"
              />
            ) : (
              <meshStandardMaterial
                attach="material"
                {...(targetIdx === 3
                  ? materials["a.grass"]
                  : materials["Material.005"])}
              />
            )}
          </mesh>
        </group>
      )}

      {holes[4] && (
        <group
          position={[0.193, -2.155, -5.336]}
          rotation={[0.261, 0, 0]}
          scale={[0.243, 0.201, 0.243]}
        >
          <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry}>
            {!dissolvingHoles[4] ? (
              <>
                <DissolveMaterial
                  baseMaterial={materials["Material.003"].clone()}
                  visible={true}
                  duration={1}
                  color="#eb5a13"
                />
              </>
            ) : (
              <meshStandardMaterial
                attach="material"
                {...(targetIdx === 4
                  ? materials["a.grass"]
                  : materials["Material.003"])}
              />
            )}
          </mesh>

          <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry}>
            {!dissolvingHoles[4] ? (
              <DissolveMaterial
                baseMaterial={materials["Material.005"].clone()}
                visible={true}
                duration={1}
                color="#eb5a13"
              />
            ) : (
              <meshStandardMaterial
                attach="material"
                {...(targetIdx === 4
                  ? materials["a.grass"]
                  : materials["Material.005"])}
              />
            )}
          </mesh>
        </group>
      )}

      {holes[5] && (
        <group
          position={[-0.008, -2.245, -4.999]}
          rotation={[0.261, 0, 0]}
          scale={[0.243, 0.201, 0.243]}
        >
          <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry}>
            {!dissolvingHoles[5] ? (
              <>
                <DissolveMaterial
                  baseMaterial={materials["Material.003"].clone()}
                  visible={true}
                  duration={1}
                  color="#eb5a13"
                />
              </>
            ) : (
              <meshStandardMaterial
                attach="material"
                {...(targetIdx === 5
                  ? materials["a.grass"]
                  : materials["Material.003"])}
              />
            )}
          </mesh>

          <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry}>
            {!dissolvingHoles[5] ? (
              <DissolveMaterial
                baseMaterial={materials["Material.005"].clone()}
                visible={true}
                duration={1}
                color="#eb5a13"
              />
            ) : (
              <meshStandardMaterial
                attach="material"
                {...(targetIdx === 5
                  ? materials["a.grass"]
                  : materials["Material.005"])}
              />
            )}
          </mesh>
        </group>
      )}
      <mesh
        geometry={nodes.Cylinder055.geometry}
        material={materials["Material.008"]}
        position={[-0.008, -2.161, -5.347]}
        rotation={[-1.309, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder056.geometry}
        material={nodes.Cylinder056.material}
        position={[-0.008, -2.161, -5.347]}
        rotation={[-1.309, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder057.geometry}
        material={materials["Material.008"]}
        position={[-0.008, -2.161, -5.347]}
        rotation={[-1.309, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder058.geometry}
        material={materials["Material.008"]}
        position={[-0.008, -2.161, -5.347]}
        rotation={[-1.309, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder059.geometry}
        material={nodes.Cylinder059.material}
        position={[-0.008, -2.161, -5.347]}
        rotation={[-1.309, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder060.geometry}
        material={materials["Material.008"]}
        position={[0.622, -2.31, -6.061]}
        rotation={[0.261, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder061.geometry}
        material={nodes.Cylinder061.material}
        position={[0.622, -2.31, -6.061]}
        rotation={[0.261, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder062.geometry}
        material={materials["Material.008"]}
        position={[0.622, -2.31, -6.061]}
        rotation={[0.261, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder063.geometry}
        material={materials["Material.008"]}
        position={[0.622, -2.31, -6.061]}
        rotation={[0.261, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder064.geometry}
        material={nodes.Cylinder064.material}
        position={[0.622, -2.31, -6.061]}
        rotation={[0.261, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials["Material.008"]}
        position={[0.644, -1.99, -5.975]}
        rotation={[-1.309, 1.571, 0]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials["Material.008"]}
        position={[0.644, -1.99, -5.975]}
        rotation={[-1.309, 1.571, 0]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials["Material.008"]}
        position={[0.644, -1.99, -5.975]}
        rotation={[-1.309, 1.571, 0]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials["Material.008"]}
        position={[0.644, -1.99, -5.975]}
        rotation={[-1.309, 1.571, 0]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials["Material.008"]}
        position={[0.644, -1.99, -5.975]}
        rotation={[-1.309, 1.571, 0]}
      />
      <mesh
        geometry={nodes.Cylinder039.geometry}
        material={materials["Material.008"]}
        position={[-0.659, -2.159, -5.343]}
        rotation={[-1.309, 0, 0]}
        scale={[0.014, 0.598, 0.014]}
      />
      <mesh
        geometry={nodes.Cylinder041.geometry}
        material={materials["Material.008"]}
        position={[-0.008, -1.99, -5.975]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.014, 0.598, 0.014]}
      />
      <mesh
        geometry={nodes.Cylinder084.geometry}
        material={materials["Material.008"]}
        position={[-0.008, -2.328, -6.066]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.014, 0.598, 0.014]}
      />
      <mesh
        geometry={nodes.Cylinder065.geometry}
        material={materials["Material.008"]}
        position={[-0.66, -2.16, -6.021]}
        rotation={[0.263, 0, -Math.PI]}
        scale={[0.014, 0.117, 0.014]}
      />
      <mesh
        geometry={nodes.Cylinder042.geometry}
        material={materials["Material.008"]}
        position={[0.644, -2.16, -6.021]}
        rotation={[0.263, 0, -Math.PI]}
        scale={[0.014, 0.117, 0.014]}
      />
      <mesh
        geometry={nodes.Circle018.geometry}
        material={materials["Material.007"]}
        position={[-0.658, -2.158, -5.346]}
        rotation={[1.832, -Math.PI / 2, 0]}
        scale={0.015}
      />
      <mesh
        geometry={nodes.Circle020.geometry}
        material={materials["Material.007"]}
        position={[-0.008, -1.99, -5.974]}
        rotation={[-2.88, 0, Math.PI / 2]}
        scale={0.015}
      />
      <mesh
        geometry={nodes.Cylinder038.geometry}
        material={materials["Material.008"]}
        position={[0.643, -2.159, -5.343]}
        rotation={[1.832, 0, Math.PI]}
        scale={[0.014, 0.598, 0.014]}
      />
      <mesh
        geometry={nodes.Circle019.geometry}
        material={materials["Material.007"]}
        position={[0.642, -2.158, -5.346]}
        rotation={[1.832, Math.PI / 2, 0]}
        scale={0.015}
      />
      <mesh
        geometry={nodes.Cylinder040.geometry}
        material={materials["Material.008"]}
        position={[-0.008, -2.327, -4.717]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
        scale={[0.014, 0.598, 0.014]}
      />
      <mesh
        geometry={nodes.Circle021.geometry}
        material={materials["Material.007"]}
        position={[-0.008, -2.326, -4.718]}
        rotation={[0.261, 0, Math.PI / 2]}
        scale={0.015}
      />
    </group>
  );
}
