/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/golfpong/gp_scene2.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import useExperience from '../hooks/useExperience'

export function GP_Scene2(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/golfpong/gp_scene2.glb')
  const { actions } = useAnimations(animations, group)
  const { holes, shotDirection } = useExperience()

  const holePriority = {
  left: [0, 3],
  center: [1, 3, 4, 5],
  right: [2, 4],
};

  return (
     <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="puttingg_green" position={[0, -2.344, 0]} scale={[0.185, 0.185, 0.186]}>
          <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials['Material.003']} />
          <mesh name="Cube020_1" geometry={nodes.Cube020_1.geometry} material={materials['a.grass']} />
        </group>
        <mesh name="platform" geometry={nodes.platform.geometry} material={materials['a.grass.001']} position={[0, -2.344, -2.775]} scale={[1.517, 3.437, 3.437]} />
        <group name="Plane016" position={[-0.008, -2.161, -5.347]} rotation={[0.261, 0, 0]}>
          <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials['Material.009']} />
          <mesh name="Plane017_1" geometry={nodes.Plane017_1.geometry} material={materials['Material.003']} />
          <mesh name="Plane017_2" geometry={nodes.Plane017_2.geometry} material={materials['Material.004']} />
          <mesh name="Circle018" geometry={nodes.Circle018.geometry} material={materials['Material.007']} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.015} />
          <mesh name="Circle019" geometry={nodes.Circle019.geometry} material={materials['Material.007']} position={[-0.65, 0.003, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.015} />
          <mesh name="Circle020" geometry={nodes.Circle020.geometry} material={materials['Material.007']} rotation={[0, 0, Math.PI / 2]} scale={0.015} />
          <mesh name="Circle021" geometry={nodes.Circle021.geometry} material={materials['Material.007']} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={0.015} />
          <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Material.008']} position={[0.652, 0.003, -0.651]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh name="Cylinder038" geometry={nodes.Cylinder038.geometry} material={materials['Material.008']} rotation={[-Math.PI / 2, 0, 0]} scale={0.015} />
          <mesh name="Cylinder039" geometry={nodes.Cylinder039.geometry} material={materials['Material.008']} position={[-0.652, 0.003, 0.004]} rotation={[-Math.PI / 2, 0, 0]} scale={0.015} />
          <mesh name="Cylinder040" geometry={nodes.Cylinder040.geometry} material={materials['Material.008']} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
          <mesh name="Cylinder041" geometry={nodes.Cylinder041.geometry} material={materials['Material.008']} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.015} />
          <group name="Cylinder043" rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
            <mesh name="Cylinder054" geometry={nodes.Cylinder054.geometry} material={materials['Material.008']} />
            <mesh name="Cylinder054_1" geometry={nodes.Cylinder054_1.geometry} material={nodes.Cylinder054_1.material} />
          </group>
          <group name="Plane017_3" position={[0.409, 0, 0.466]} scale={[0.212, 0.212, 0.183]}>
            <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials['Material.002']} />
            <mesh name="Plane018_1" geometry={nodes.Plane018_1.geometry} material={materials['Material.010']} />
          </group>
          {holes[5] && (
          <group name="ring1" position={[0, 0.009, 0.358]} scale={[0.243, 0.201, 0.243]}>
            <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry} material={materials['Material.003']} />
            <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry} material={
        holePriority[shotDirection]?.includes(5)
          ? materials['a.grass.001']
          : materials['Material.005']
      } />
          </group>
          )}
          {holes[3] && (
          <group name="ring2" position={[-0.202, 0.009, 0.008]} scale={[0.243, 0.201, 0.243]}>
            <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry} material={materials['Material.003']} />
            <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry} material={
        holePriority[shotDirection]?.includes(3)
          ? materials['a.grass.001']
          : materials['Material.005']
      } />
          </group>
          )}
          {holes[4] && (
          <group name="ring3" position={[0.201, 0.009, 0.008]} scale={[0.243, 0.201, 0.243]}>
            <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry} material={materials['Material.003']} />
            <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry} material={
        holePriority[shotDirection]?.includes(4)
          ? materials['a.grass.001']
          : materials['Material.005']
      } />
          </group>
          )}
          {holes[0] && (
          <group name="ring4" position={[-0.403, 0.009, -0.34]} scale={[0.243, 0.201, 0.243]}>
            <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry} material={materials['Material.003']} />
            <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry} material={
        holePriority[shotDirection]?.includes(0)
          ? materials['a.grass.001']
          : materials['Material.005']
      } />
          </group>
          )}
          {holes[1] && (
          <group name="ring5" position={[0.001, 0.009, -0.34]} scale={[0.243, 0.201, 0.243]}>
            <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry} material={materials['Material.003']} />
            <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry} material={
        holePriority[shotDirection]?.includes(1)
          ? materials['a.grass.001']
          : materials['Material.005']
      } />
          </group>
          )}
          {holes[2] && (
          <group name="ring6" position={[0.403, 0.009, -0.34]} scale={[0.243, 0.201, 0.243]}>
            <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry} material={materials['Material.003']} />
            <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry} material={
        holePriority[shotDirection]?.includes(2)
          ? materials['a.grass.001']
          : materials['Material.005']
      } />
          </group>
          )}
        </group>
        <mesh name="Cylinder042" geometry={nodes.Cylinder042.geometry} material={materials['Material.008']} position={[0.644, -2.158, -6.02]} rotation={[0.261, Math.PI / 2, 0]} scale={[0.015, 0.013, 0.015]} />
        <group name="Cylinder044" position={[0.622, -2.31, -6.061]} rotation={[0.261, 0, -Math.PI / 2]}>
          <mesh name="Cylinder055" geometry={nodes.Cylinder055.geometry} material={materials['Material.008']} />
          <mesh name="Cylinder055_1" geometry={nodes.Cylinder055_1.geometry} material={nodes.Cylinder055_1.material} />
        </group>
        <mesh name="Cylinder045" geometry={nodes.Cylinder045.geometry} material={materials['Material.008']} position={[-0.008, -2.332, -6.717]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
        {/* <group name="ball1" position={[0, -2.273, 0]} rotation={[0, -1.556, 0]} scale={0.038}>
          <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials.Material} />
          <mesh name="Cube011_1" geometry={nodes.Cube011_1.geometry} material={materials['Material.001']} />
        </group> */}
        <group name="ball3" position={[0, -2.273, 0]} rotation={[0, -1.556, 0]} scale={0.038}>
          <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.Material} />
          <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['Material.001']} />
        </group>
      </group>
    </group>
  )
}

