/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/golfpong/gp_scene2.glb -keepnames --keepgroups 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function GP_Test(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/golfpong/gp_targetmat.glb')
  const { actions } = useAnimations(animations, group)
  return (
     <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Plane016" position={[-0.008, -2.161, -5.347]} rotation={[0.261, 0, 0]}>
          <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials['Material.009']} />
          <mesh name="Plane017_1" geometry={nodes.Plane017_1.geometry} material={materials['Material.003']} />
          <mesh name="Plane017_2" geometry={nodes.Plane017_2.geometry} material={materials['Material.004']} />
        </group>
        <group name="logo" position={[0.401, -2.281, -4.896]} rotation={[0.261, 0, 0]} scale={[0.212, 0.212, 0.183]}>
          <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials['Material.002']} />
          <mesh name="Plane018_1" geometry={nodes.Plane018_1.geometry} material={materials['Material.010']} />
        </group>
        <mesh name="Circle018" geometry={nodes.Circle018.geometry} material={materials['Material.007']} position={[-0.008, -2.161, -5.347]} rotation={[1.832, 1.571, 0]} scale={0.015} />
        <mesh name="Circle019" geometry={nodes.Circle019.geometry} material={materials['Material.007']} position={[-0.658, -2.158, -5.346]} rotation={[1.832, -Math.PI / 2, 0]} scale={0.015} />
        <mesh name="Circle020" geometry={nodes.Circle020.geometry} material={materials['Material.007']} position={[-0.008, -2.161, -5.347]} rotation={[0.261, 0, Math.PI / 2]} scale={0.015} />
        <mesh name="Circle021" geometry={nodes.Circle021.geometry} material={materials['Material.007']} position={[-0.008, -2.161, -5.347]} rotation={[-2.88, 0, -Math.PI / 2]} scale={0.015} />
        <mesh name="Cylinder038" geometry={nodes.Cylinder038.geometry} material={materials['Material.008']} position={[-0.008, -2.161, -5.347]} rotation={[-1.309, 0, 0]} scale={0.015} />
        <mesh name="Cylinder039" geometry={nodes.Cylinder039.geometry} material={materials['Material.008']} position={[-0.659, -2.159, -5.342]} rotation={[-1.309, 0, 0]} scale={0.015} />
        <mesh name="Cylinder040" geometry={nodes.Cylinder040.geometry} material={materials['Material.008']} position={[-0.008, -2.161, -5.347]} rotation={[-1.309, 0, -Math.PI / 2]} scale={0.015} />
        <mesh name="Cylinder041" geometry={nodes.Cylinder041.geometry} material={materials['Material.008']} position={[-0.008, -2.161, -5.347]} rotation={[-1.309, 0, Math.PI / 2]} scale={0.015} />
        <mesh name="Cylinder042" geometry={nodes.Cylinder042.geometry} material={materials['Material.008']} position={[0.644, -2.158, -6.02]} rotation={[0.261, Math.PI / 2, 0]} scale={[0.015, 0.013, 0.015]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Material.008']} position={[0.644, -1.99, -5.975]} rotation={[-1.309, 1.571, 0]} />
        <mesh name="Cylinder043" geometry={nodes.Cylinder043.geometry} material={materials['Material.008']} position={[-0.008, -2.161, -5.347]} rotation={[-1.309, 0, -Math.PI / 2]} />
        <mesh name="Cylinder044" geometry={nodes.Cylinder044.geometry} material={materials['Material.008']} position={[0.622, -2.31, -6.061]} rotation={[0.261, 0, -Math.PI / 2]} />
        <mesh name="Cylinder045" geometry={nodes.Cylinder045.geometry} material={materials['Material.008']} position={[-0.008, -2.332, -6.717]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
        <group name="ring4" position={[-0.411, -2.065, -5.673]} rotation={[0.261, 0, 0]} scale={[0.243, 0.201, 0.243]}>
          <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry} material={materials['Material.003']} />
          <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry} material={materials['Material.005']} />
        </group>
        <group name="ring5" position={[-0.007, -2.065, -5.673]} rotation={[0.261, 0, 0]} scale={[0.243, 0.201, 0.243]}>
          <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry} material={materials['Material.003']} />
          <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry} material={materials['Material.005']} />
        </group>
        <group name="ring6" position={[0.395, -2.065, -5.673]} rotation={[0.261, 0, 0]} scale={[0.243, 0.201, 0.243]}>
          <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry} material={materials['Material.003']} />
          <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry} material={materials['Material.005']} />
        </group>
        <group name="ring2" position={[-0.21, -2.155, -5.336]} rotation={[0.261, 0, 0]} scale={[0.243, 0.201, 0.243]}>
          <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry} material={materials['Material.003']} />
          <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry} material={materials['Material.005']} />
        </group>
        <group name="ring3" position={[0.193, -2.155, -5.336]} rotation={[0.261, 0, 0]} scale={[0.243, 0.201, 0.243]}>
          <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry} material={materials['Material.003']} />
          <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry} material={materials['Material.005']} />
        </group>
        <group name="ring1" position={[-0.008, -2.245, -4.999]} rotation={[0.261, 0, 0]} scale={[0.243, 0.201, 0.243]}>
          <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry} material={materials['Material.003']} />
          <mesh name="Cylinder052_1" geometry={nodes.Cylinder052_1.geometry} material={materials['Material.005']} />
        </group>
        <mesh name="Cylinder054" geometry={nodes.Cylinder054.geometry} material={materials['Material.008']} position={[-0.66, -2.158, -6.02]} rotation={[0.261, Math.PI / 2, 0]} scale={[0.015, 0.013, 0.015]} />
        <mesh name="Cylinder055" geometry={nodes.Cylinder055.geometry} material={materials['Material.008']} position={[-0.008, -2.161, -5.347]} rotation={[-1.309, 0, -Math.PI / 2]} />
        <mesh name="Cylinder056" geometry={nodes.Cylinder056.geometry} material={nodes.Cylinder056.material} position={[-0.008, -2.161, -5.347]} rotation={[-1.309, 0, -Math.PI / 2]} />
        <mesh name="Cylinder057" geometry={nodes.Cylinder057.geometry} material={materials['Material.008']} position={[-0.008, -2.161, -5.347]} rotation={[-1.309, 0, -Math.PI / 2]} />
        <mesh name="Cylinder058" geometry={nodes.Cylinder058.geometry} material={materials['Material.008']} position={[-0.008, -2.161, -5.347]} rotation={[-1.309, 0, -Math.PI / 2]} />
        <mesh name="Cylinder059" geometry={nodes.Cylinder059.geometry} material={nodes.Cylinder059.material} position={[-0.008, -2.161, -5.347]} rotation={[-1.309, 0, -Math.PI / 2]} />
        <mesh name="Cylinder060" geometry={nodes.Cylinder060.geometry} material={materials['Material.008']} position={[0.622, -2.31, -6.061]} rotation={[0.261, 0, -Math.PI / 2]} />
        <mesh name="Cylinder061" geometry={nodes.Cylinder061.geometry} material={nodes.Cylinder061.material} position={[0.622, -2.31, -6.061]} rotation={[0.261, 0, -Math.PI / 2]} />
        <mesh name="Cylinder062" geometry={nodes.Cylinder062.geometry} material={materials['Material.008']} position={[0.622, -2.31, -6.061]} rotation={[0.261, 0, -Math.PI / 2]} />
        <mesh name="Cylinder063" geometry={nodes.Cylinder063.geometry} material={materials['Material.008']} position={[0.622, -2.31, -6.061]} rotation={[0.261, 0, -Math.PI / 2]} />
        <mesh name="Cylinder064" geometry={nodes.Cylinder064.geometry} material={nodes.Cylinder064.material} position={[0.622, -2.31, -6.061]} rotation={[0.261, 0, -Math.PI / 2]} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Material.008']} position={[0.644, -1.99, -5.975]} rotation={[-1.309, 1.571, 0]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Material.008']} position={[0.644, -1.99, -5.975]} rotation={[-1.309, 1.571, 0]} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['Material.008']} position={[0.644, -1.99, -5.975]} rotation={[-1.309, 1.571, 0]} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['Material.008']} position={[0.644, -1.99, -5.975]} rotation={[-1.309, 1.571, 0]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['Material.008']} position={[0.644, -1.99, -5.975]} rotation={[-1.309, 1.571, 0]} />
      </group>
    </group>
  )
}


